export const ADD='ADD';
export const REMOVE='REMOVE';
export const ALL='ALL';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const BUY_PRODUCTS='BUY_PRODUCTS';   
export const BUY_PRODUCTS_FAIL='BUY_PRODUCTS_FAIL';
export const BUY_PRODUCTS_SUCCESS='BUY_PRODUCTS_SUCCESS';
